In [1]:
from sensitivity import * 
import pandas as pd

In [2]:
transaction_user=pd.read_csv("./data_csv/transaction-user.csv")

In [3]:
EntropyofAttribute(transaction_user)

             Entropy of Attribute
age                      0.615963
gender                   0.654699
height                   0.550845
weight                   0.532532
ap_hi                    0.684323
ap_lo                    0.679760
cholesterol              0.679760
gluc                     0.670009
smoke                    0.635329
alco                     0.651757
active                   0.631694
cardio                   0.670009
BMI                      0.631694
BMICat                   0.654699
pneumonia                0.689812
diabetes                 0.550845
copd                     0.624069
asthma                   0.532532
inmsupr                  0.598270
city                     0.611726
Married                  0.400867
Medicine                 0.688924

In [4]:
EntropyofUsability(transaction_user)

             Entropy of Usability
age                      0.360760
gender                   0.353533
height                   0.222057
weight                   0.222276
ap_hi                    0.273138
ap_lo                    0.267906
cholesterol              0.269303
gluc                     0.266022
smoke                    0.245377
alco                     0.252821
active                   0.242186
cardio                   0.262663
BMI                      0.239948
BMICat                   0.254268
pneumonia                0.337809
diabetes                 0.366103
copd                     0.364204
asthma                   0.366961
inmsupr                  0.365735
city                     0.275720
Married                  0.187092
Medicine                 0.347578

In [5]:
EntropyofAssociativity(transaction_user)

             Entropy of associativity
age                          0.217821
gender                       0.192831
height                       0.089600
weight                       0.084050
ap_hi                        0.137562
ap_lo                        0.133265
cholesterol                  0.133265
gluc                         0.118227
smoke                        0.111871
alco                         0.121329
active                       0.111871
cardio                       0.128873
BMI                          0.106962
BMICat                       0.116658
pneumonia                    0.165287
diabetes                     0.188504
copd                         0.171354
asthma                       0.191759
inmsupr                      0.184077
city                         0.106962
Married                      0.053129
Medicine                     0.133265

In [6]:
combinedentropy(transaction_user)

             Combined Entropy
age                  0.048403
gender               0.044632
height               0.010960
weight               0.009949
ap_hi                0.025712
ap_lo                0.024269
cholesterol          0.024396
gluc                 0.021073
smoke                0.017440
alco                 0.019992
active               0.017115
cardio               0.022680
BMI                  0.016213
BMICat               0.019420
pneumonia            0.038516
diabetes             0.038015
copd                 0.038947
asthma               0.037473
inmsupr              0.040277
city                 0.018041
Married              0.003985
Medicine             0.031911

In [7]:
Sensitivity(0.035,transaction_user)

      Attribute Sensitive
0           age       Yes
1        gender       Yes
2        height        No
3        weight        No
4         ap_hi        No
5         ap_lo        No
6   cholesterol        No
7          gluc        No
8         smoke        No
9          alco        No
10       active        No
11       cardio        No
12          BMI        No
13       BMICat        No
14    pneumonia       Yes
15     diabetes       Yes
16         copd       Yes
17       asthma       Yes
18      inmsupr       Yes
19         city        No
20      Married        No
21     Medicine        No

In [8]:
transaction_user_1=pd.read_csv("./data_csv/transaction-user_1.csv")

In [9]:
EntropyofAttribute(transaction_user_1)

                 Entropy of Attribute
age                          0.615963
gender                       0.654699
height                       0.550845
weight                       0.532532
ap_hi                        0.684323
ap_lo                        0.679760
cholesterol                  0.679760
gluc                         0.670009
smoke                        0.635329
alco                         0.651757
active                       0.631694
cardio                       0.670009
BMI                          0.631694
BMICat                       0.654699
pneumonia                    0.689812
diabetes                     0.550845
copd                         0.624069
asthma                       0.532532
inmsupr                      0.598270
city                         0.611726
Married                      0.400867
Medicine                     0.688924
blood group                  0.634588
pulse rate                   0.678010
disease details              0.650709
b lood report                0.254280
USG                          0.589963

In [10]:
EntropyofUsability(transaction_user_1)

                 Entropy of Usability
age                          0.338283
gender                       0.327210
height                       0.191473
weight                       0.191274
ap_hi                        0.242158
ap_lo                        0.237202
cholesterol                  0.238389
gluc                         0.234752
smoke                        0.215269
alco                         0.222396
active                       0.212440
cardio                       0.231908
BMI                          0.210598
BMICat                       0.223787
pneumonia                    0.307531
diabetes                     0.351381
copd                         0.346772
asthma                       0.353782
inmsupr                      0.349958
city                         0.243935
Married                      0.161624
Medicine                     0.325162
blood group                  0.210883
pulse rate                   0.234875
disease details              0.216818
b lood report                0.365302
USG                          0.341347

In [11]:
EntropyofAssociativity(transaction_user_1)

                 Entropy of associativity
age                              0.187405
gender                           0.164686
height                           0.074502
weight                           0.069788
ap_hi                            0.115774
ap_lo                            0.112036
cholesterol                      0.112036
gluc                             0.099019
smoke                            0.093546
alco                             0.101695
active                           0.093546
cardio                           0.108224
BMI                              0.089331
BMICat                           0.097666
pneumonia                        0.140106
diabetes                         0.160795
copd                             0.145483
asthma                           0.163720
inmsupr                          0.156825
city                             0.089331
Married                          0.043743
Medicine                         0.112036
blood group                      0.099019
pulse rate                       0.109503
disease details                  0.092152
b lood report                    0.184814
USG                              0.181305

In [12]:
Sensitivity(0.025,transaction_user_1)

          Attribute Sensitive
0               age       Yes
1            gender       Yes
2            height        No
3            weight        No
4             ap_hi        No
5             ap_lo        No
6       cholesterol        No
7              gluc        No
8             smoke        No
9              alco        No
10           active        No
11           cardio        No
12              BMI        No
13           BMICat        No
14        pneumonia       Yes
15         diabetes       Yes
16             copd       Yes
17           asthma       Yes
18          inmsupr       Yes
19             city        No
20          Married        No
21         Medicine       Yes
22      blood group        No
23       pulse rate        No
24  disease details        No
25    b lood report        No
26              USG       Yes

In [13]:
ce=combinedentropy(transaction_user)
s=Sensitivity(0.035,transaction_user).set_index('Attribute')
df=pd.concat([ce,s],axis=1,join='inner')
df

             Combined Entropy Sensitive
age                  0.048403       Yes
gender               0.044632       Yes
height               0.010960        No
weight               0.009949        No
ap_hi                0.025712        No
ap_lo                0.024269        No
cholesterol          0.024396        No
gluc                 0.021073        No
smoke                0.017440        No
alco                 0.019992        No
active               0.017115        No
cardio               0.022680        No
BMI                  0.016213        No
BMICat               0.019420        No
pneumonia            0.038516       Yes
diabetes             0.038015       Yes
copd                 0.038947       Yes
asthma               0.037473       Yes
inmsupr              0.040277       Yes
city                 0.018041        No
Married              0.003985        No
Medicine             0.031911        No

In [14]:
ce=combinedentropy(transaction_user_1)
s=Sensitivity(0.025,transaction_user_1).set_index('Attribute')
df=pd.concat([ce,s],axis=1,join='inner')
df

                 Combined Entropy Sensitive
age                      0.039049       Yes
gender                   0.035280       Yes
height                   0.007858        No
weight                   0.007109        No
ap_hi                    0.019185        No
ap_lo                    0.018065        No
cholesterol              0.018155        No
gluc                     0.015574        No
smoke                    0.012794        No
alco                     0.014741        No
active                   0.012554        No
cardio                   0.016816        No
BMI                      0.011884        No
BMICat                   0.014309        No
pneumonia                0.029722       Yes
diabetes                 0.031123       Yes
copd                     0.031484       Yes
asthma                   0.030845       Yes
inmsupr                  0.032834       Yes
city                     0.013330        No
Married                  0.002834        No
Medicine                 0.025097       Yes
blood group              0.013251        No
pulse rate               0.017438        No
disease details          0.013001        No
b lood report            0.017167        No
USG                      0.036512       Yes

In [16]:
Associativity(transaction_user)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,...,BMI,BMICat,pneumonia,diabetes,copd,asthma,inmsupr,city,Married,Medicine
age,136,111,36,33,66,63,63,53,49,55,...,46,52,87,107,92,110,103,46,18,63
gender,111,125,39,44,66,63,59,51,46,51,...,47,52,95,104,100,110,111,44,18,54
height,36,39,47,23,33,33,33,25,15,18,...,28,29,26,39,27,39,34,24,2,27
weight,33,44,23,44,28,28,28,21,22,17,...,14,15,41,42,41,42,36,12,6,23
ap_hi,66,66,33,28,85,78,78,66,57,66,...,64,71,66,83,66,81,70,19,9,57
ap_lo,63,63,33,28,78,82,73,61,50,59,...,59,64,63,80,63,78,67,23,9,57
cholesterol,63,59,33,28,78,73,82,70,56,59,...,57,64,62,76,60,74,63,17,9,54
gluc,53,51,25,21,66,61,70,77,51,55,...,49,56,53,64,51,62,57,20,9,42
smoke,49,46,15,22,57,50,56,51,65,40,...,36,43,56,55,55,53,50,7,9,37
alco,55,51,18,17,66,59,59,55,40,70,...,51,57,51,68,51,66,60,20,5,42
active,49,53,19,20,61,57,56,45,47,46,...,45,51,59,62,59,60,57,7,7,39
cardio,60,58,30,26,73,66,73,62,53,56,...,53,59,59,71,58,69,62,16,9,49
BMI,46,47,28,14,64,59,57,49,36,51,...,64,64,45,62,45,60,53,14,5,43
BMICat,52,52,29,15,71,64,64,56,43,57,...,64,71,52,69,52,67,60,15,5,43
pneumonia,87,95,26,41,66,63,62,53,56,51,...,45,52,106,94,104,96,94,24,18,42
diabetes,107,104,39,42,83,80,76,64,55,68,...,62,69,94,149,118,141,121,42,16,92
copd,92,100,27,41,66,63,60,51,55,51,...,45,52,104,118,134,118,113,29,24,69
asthma,110,110,39,42,81,78,74,62,53,66,...,60,67,96,141,118,152,123,46,15,91
inmsupr,103,111,34,36,70,67,63,57,50,60,...,53,60,94,121,113,123,140,47,20,74
city,46,44,24,12,19,23,17,20,7,20,...,14,15,24,42,29,46,47,59,2,32
Married,18,18,2,6,9,9,9,9,9,5,...,5,5,18,16,24,15,20,2,27,20
Medicine,63,54,27,23,57,57,54,42,37,42,...,43,43,42,92,69,91,74,32,20,107

In [17]:
usability(transaction_user)

               Doctor  Pathologist  Pharmasist  Researcher
age          0.062901     0.161184    0.016340    0.057491
gender       0.052632     0.134868    0.016340    0.066202
height       0.026958     0.036184    0.009804    0.020906
weight       0.020539     0.042763    0.009804    0.020906
ap_hi        0.062901     0.000000    0.026144    0.048780
ap_lo        0.062901     0.000000    0.026144    0.043554
cholesterol  0.059050     0.000000    0.026144    0.048780
gluc         0.043646     0.000000    0.026144    0.060976
smoke        0.037227     0.000000    0.026144    0.048780
alco         0.043646     0.000000    0.026144    0.048780
active       0.039795     0.000000    0.026144    0.043554
cardio       0.052632     0.000000    0.026144    0.048780
BMI          0.044929     0.000000    0.026144    0.036585
BMICat       0.044929     0.000000    0.026144    0.048780
pneumonia    0.038511     0.098684    0.026144    0.066202
diabetes     0.062901     0.092105    0.111111    0.066202
copd         0.041078     0.105263    0.104575    0.066202
asthma       0.062901     0.101974    0.111111    0.066202
inmsupr      0.046213     0.118421    0.098039    0.066202
city         0.019255     0.049342    0.045752    0.026132
Married      0.011553     0.029605    0.029412    0.000000
Medicine     0.062901     0.029605    0.160131    0.000000

In [18]:
EntropyofAssociativity(transaction_user)

             Entropy of associativity
age                          0.217821
gender                       0.192831
height                       0.089600
weight                       0.084050
ap_hi                        0.137562
ap_lo                        0.133265
cholesterol                  0.133265
gluc                         0.118227
smoke                        0.111871
alco                         0.121329
active                       0.111871
cardio                       0.128873
BMI                          0.106962
BMICat                       0.116658
pneumonia                    0.165287
diabetes                     0.188504
copd                         0.171354
asthma                       0.191759
inmsupr                      0.184077
city                         0.106962
Married                      0.053129
Medicine                     0.133265

In [19]:
def EntropyofAssociativity(dataset):
    s=0
    e=[] 
    elem='User'
    columns=dataset.columns.to_list()
    if elem in columns:
        columns.remove(elem)
    associativity=pd.DataFrame()
    for i in range(len(columns)):
        y=pd.DataFrame()
        #Grouping the whole dataset in parts according to each attribute AND #Extract each attribute's 'yes' data by iterating loop 
        x=dataset.groupby(columns[i]).get_group(1).reset_index().drop(['index','User'],axis=1)
        r=x.shape[1]
        #Counting yes of one attribute repect to another attribute
        y=pd.DataFrame.from_dict(counting_yes(x,0,r),orient='index').rename(columns={0:columns[i]})
        #Storing all values in dataframe
        associativity=pd.concat([associativity,y],axis=1)
    # Calculate probability of associativity by calling the function
    associativity=Associativity(dataset)
    #Summation of probability of associativity of each attribute 
    associativity['sum_']=associativity.sum(axis=1)
    r=associativity.shape[1]
    #Using Entropy formula to calculate of entropy of associativity each attribute
    for i in range(0,r-1):
        for j in range(i,r-1):
            if(associativity.iat[i,j]!=0):
                s=s+(-((associativity.iat[i,j]/associativity.iat[i,r-1])*math.log((associativity.iat[i,j]/associativity.iat[i,r-1]))))
                e.append(s)
                s=0
    # Store the values in dictionary {Attribute name :Entropy of Associativity} 
    H={associativity.T.columns[i]:e[i] for i in range(len(associativity.T.columns))}
     #present in dataframe 
    associativity_entropy_df=pd.DataFrame.from_dict(H,orient='index').rename(columns={0:'Entropy of associativity'})
    return associativity_entropy_df

In [20]:
EntropyofAssociativity(transaction_user)

             Entropy of associativity
age                          0.217821
gender                       0.192831
height                       0.089600
weight                       0.084050
ap_hi                        0.137562
ap_lo                        0.133265
cholesterol                  0.133265
gluc                         0.118227
smoke                        0.111871
alco                         0.121329
active                       0.111871
cardio                       0.128873
BMI                          0.106962
BMICat                       0.116658
pneumonia                    0.165287
diabetes                     0.188504
copd                         0.171354
asthma                       0.191759
inmsupr                      0.184077
city                         0.106962
Married                      0.053129
Medicine                     0.133265

In [21]:
usability(transaction_user)

               Doctor  Pathologist  Pharmasist  Researcher
age          0.062901     0.161184    0.016340    0.057491
gender       0.052632     0.134868    0.016340    0.066202
height       0.026958     0.036184    0.009804    0.020906
weight       0.020539     0.042763    0.009804    0.020906
ap_hi        0.062901     0.000000    0.026144    0.048780
ap_lo        0.062901     0.000000    0.026144    0.043554
cholesterol  0.059050     0.000000    0.026144    0.048780
gluc         0.043646     0.000000    0.026144    0.060976
smoke        0.037227     0.000000    0.026144    0.048780
alco         0.043646     0.000000    0.026144    0.048780
active       0.039795     0.000000    0.026144    0.043554
cardio       0.052632     0.000000    0.026144    0.048780
BMI          0.044929     0.000000    0.026144    0.036585
BMICat       0.044929     0.000000    0.026144    0.048780
pneumonia    0.038511     0.098684    0.026144    0.066202
diabetes     0.062901     0.092105    0.111111    0.066202
copd         0.041078     0.105263    0.104575    0.066202
asthma       0.062901     0.101974    0.111111    0.066202
inmsupr      0.046213     0.118421    0.098039    0.066202
city         0.019255     0.049342    0.045752    0.026132
Married      0.011553     0.029605    0.029412    0.000000
Medicine     0.062901     0.029605    0.160131    0.000000